### ISSUE TITLE
idPrefix is not taken from the fields JSON

### ISSUE THREAD

**Issue by Jimmy-Newtron** [jzcling/react-material-ui-form-builder#6]
https://github.com/jzcling/react-material-ui-form-builder/blob/94b47de88cb817e761c3b3e4b0845c2070ca4310/src/Components/FormBuilder.tsx#L61

This method is not taking into account the fieldProp idPrefix so the README example gives the following error

![image](https://user-images.githubusercontent.com/24460646/160784067-d4facbfe-9c34-4c79-ba9a-f645e00be23a.png)

**Comment by jzcling** [comment]
fixed this 1.1.7
